# Generated by Django 5.2 on 2025-04-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricetta',
            name='chef',
            field=models.CharField(max_length=100),
        ),
        migrations.RenameField(
            model_name='preferito',
            old_name='utente',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='preferito',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='profilo',
            name='data_nascita',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ricetta',
            name='immagine',
            field=models.ImageField(upload_to='immagini/'),
        ),
        migrations.AlterField(
            model_name='ricetta',
            name='titolo',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Concorrente',
        ),
    ]
