# Generated by Django 5.2 on 2025-04-15 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0002_alter_ricetta_chef_rename_utente_preferito_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Concorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ricetta',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricette.chef'),
        ),
        migrations.AddField(
            model_name='ricetta',
            name='concorrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ricette.concorrente'),
        ),
    ]
