# Generated by Django 5.2 on 2025-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0003_chef_concorrente_alter_ricetta_chef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='cognome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='stelle_michelin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='cognome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='eta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='professione',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
