# Generated by Django 5.2 on 2025-04-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0004_chef_cognome_chef_stelle_michelin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricetta',
            name='chef',
        ),
    ]
