# Generated by Django 5.2 on 2025-04-18 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0005_remove_ricetta_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='foto',
            field=models.ImageField(default='immagini/default_chef.jpg', upload_to='immagini/foto_chef/'),
        ),
        migrations.AddField(
            model_name='concorrente',
            name='foto',
            field=models.ImageField(default='immagini/default_concorrente.jpg', upload_to='immagini/foto_concorrenti/'),
        ),
        migrations.AddField(
            model_name='ricetta',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ricette.chef'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='cognome',
            field=models.CharField(blank=True, default='Sconosciuto', max_length=100),
        ),
        migrations.AlterField(
            model_name='concorrente',
            name='cognome',
            field=models.CharField(blank=True, default='Sconosciuto', max_length=100),
        ),
        migrations.AlterField(
            model_name='concorrente',
            name='eta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='concorrente',
            name='professione',
            field=models.CharField(blank=True, default='Non specificata', max_length=100),
        ),
    ]
