# Generated by Django 5.2 on 2025-05-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0006_chef_foto_concorrente_foto_ricetta_chef_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricetta',
            name='chef',
        ),
        migrations.AddField(
            model_name='ricetta',
            name='giudici',
            field=models.ManyToManyField(blank=True, related_name='ricette_giudicate', to='ricette.chef'),
        ),
    ]
