# Generated by Django 5.2 on 2025-05-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0007_remove_ricetta_chef_ricetta_giudici'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profilo',
        ),
    ]
